### ISSUE TITLE
Use environment variable to allow easy overwriting of old snapshots

### ISSUE THREAD

**Issue by coralvanda** [StratoDem/dash-snapshot-testing#3]
## Description

Use environment variable to allow easy overwriting of old snapshots
## User Story

As a developer, when I make changes that require new snapshots, I want the process of updating the snapshots to be as quick and easy as possible.

**Comment by mjclawar** [comment]
What should the environment variable be named?

Maybe run with:
```bash
$ UPDATE_DASH_SNAPSHOTS=true python -m unittest discover -s /path/to/my/project/repo
```
