### ISSUE TITLE
Log more detailed error messages when snapshots do not match

### ISSUE THREAD

**Issue by mjclawar** [StratoDem/dash-snapshot-testing#5]
## Description

For a relatively large snapshot, the error messages are not very useful (only tell the user that the strings are different, and do not give specific locations of differences).

Ideally add specifics of **what changed** between the snapshots, and where, using some difference between `OrderedDict`/`dict` objects for component snapshots.

**Comment by coralvanda** [comment]
When logging error messages to show the difference between a snapshot and the present state of a component, I think it is going to be important to be able to indicate where a particular difference has been found, so the person running tests does not need to spend extra time locating where the difference is in the code.

The best idea I have so far is to build out a skeleton of the structure in the error messages (only if a difference has been found) that shows the basic layout of the element tags on the page, and give each item a unique number which we can then match up with the differences.

An example structure:
```
1 - <div>
2 -     <div>
3 -        <p>
4 -        <p>
5 -     <div>
```

Then, if a difference is found in one of the `p` tags, it can say something like
```
4.
snapshot content: "abc"
new content: "xyz"
```

**Comment by coralvanda** [comment]
For the time being, the code on `5-detailed-errors` is only helpful if the changes are relatively simple, such as the wording in an element changed. Larger changes to the structure still cause a failure, but do not produce a helpful error message. More detailed/clever logic would be required to produce a useful error message when the changes become more involved.   

An example of the current code's error message:

```
FAILED (failures=1)
ERROR:root:Component skeleton:
1 -   type - Div
2 -   props - {'children': [{'type': 'P', 'props': {'children': 'wow'}, 'namespace': 'dash_html_components'}, {'type': 'Span', 'props': {'children': 'another one'}, 'namespace': 'dash_html_components'}], 'id': 'test-id'}
3 -     children - [{'type': 'P', 'props': {'children': 'wow'}, 'namespace': 'dash_html_components'}, {'type': 'Span', 'props': {'children': 'another one'}, 'namespace': 'dash_html_components'}]
4 -       type - P
5 -       props - {'children': 'wow'}
6 -         children - wow
7 -       namespace - dash_html_components
8 -       type - Span
9 -       props - {'children': 'another one'}
10 -         children - another one
11 -       namespace - dash_html_components
12 -     id - test-id
13 -   namespace - dash_html_components


Failure
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.5/unittest/case.py", line 600, in run
    testMethod()
  File "/home/eric/Projects/dash-snapshot-testing/snapshot_test/__tests__/test_snapshot_test_case.py", line 32, in test_component
    self.assertSnapshotEqual(my_component, 'my-test-unique-id')
  File "/home/eric/Projects/dash-snapshot-testing/snapshot_test/snapshot_test_case.py", line 76, in assertSnapshotEqual
    raise e
  File "/home/eric/Projects/dash-snapshot-testing/snapshot_test/snapshot_test_case.py", line 68, in assertSnapshotEqual
    self.assertEqual(snapshot_dict, component_dict)
  File "/usr/lib/python3.5/unittest/case.py", line 820, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.5/unittest/case.py", line 1111, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.5/unittest/case.py", line 665, in fail
    raise self.failureException(msg)
AssertionError: The following differences were found:
Element element_id: 10
  Snapshot: another one
  Component: anotherone



Process finished with exit code 1
```
